package com.hotelbooking.auth.domain;

public enum AuthErrorCode {

    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
    PASSWORD_EXPIRED,
    INVALID_CURRENT_PASSWORD,
    WEAK_PASSWORD,
    ACCESS_DENIED,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    VALIDATION_ERROR,
    INSUFFICIENT_ROLE,
    INVALID_PASSWORD_POLICY,
    MISSING_REQUIRED_FIELD,
    INTERNAL_ERROR
}